/**
 * Anthropic pricing helper — compute costCents from token counts.
 *
 * Per /docs/PRODUCT_2.0_COSTS.md §2 (May 2026 working assumptions —
 * verify against current Anthropic pricing page before billing-critical
 * use). This is the single source of truth for cost computation; any
 * call site that bills CostEvents from token usage uses this function.
 *
 * BILLING MODEL
 * -------------
 *
 * Anthropic's billing has three rates per model:
 *   - Base input: standard input tokens
 *   - Cached input: tokens served from the prompt cache (5-min TTL).
 *     ~10% of base input price. Major cost lever (see costs doc §6.1).
 *   - Output: response tokens generated by the model.
 *
 * In the API response:
 *   - inputTokens = total input tokens (cached + uncached)
 *   - cachedTokens = subset served from cache
 *   - outputTokens = response tokens
 *
 * Billing formula:
 *   uncached = inputTokens - cachedTokens
 *   cost = uncached × inputRate + cachedTokens × cachedRate
 *        + outputTokens × outputRate
 *
 * Returned as decimal cents (not integer cents) — Haiku calls cost
 * fractions of a cent and rounding to integer would lose signal.
 * Float drift is acceptable per-call; aggregate cents-denominated
 * sums stay accurate over millions of events (see costs doc §7.4).
 */

import type { ModelTier } from '../agents/tools/types';

// ===== Pricing table (USD per 1M tokens) =====

/**
 * Per-model pricing in USD per million tokens. Mirrors costs doc §2.
 *
 * Update this table when Anthropic publishes new prices. Tests assert
 * against these constants so price changes are explicit code changes.
 */
export const ANTHROPIC_PRICING_USD_PER_M_TOKENS: Record<
  ModelTier,
  { input: number; output: number; cached: number }
> = {
  haiku: { input: 1, output: 5, cached: 0.1 },
  sonnet: { input: 3, output: 15, cached: 0.3 },
  opus: { input: 15, output: 75, cached: 1.5 },
};

// ===== Input shape =====

export interface AnthropicCostInput {
  /** Model tier — selects the pricing row. */
  tier: ModelTier;
  /** Total input tokens (cached + uncached). */
  inputTokens: number;
  /** Output (response) tokens. */
  outputTokens: number;
  /** Cached input tokens (subset of inputTokens). Optional. Defaults to 0. */
  cachedTokens?: number;
}

// ===== Public function =====

/**
 * Compute the cost of an Anthropic API call in DECIMAL CENTS.
 *
 * Cents (not dollars) per the substrate-vs-cost-events doc convention
 * — sums of thousands of small calls stay numerically stable.
 *
 * Examples:
 *   - Haiku call, 1500 input / 300 output / 1500 cached:
 *       uncached = 0
 *       cost_$ = (0 × 1 + 300 × 5 + 1500 × 0.1) / 1M = $0.00165
 *       cost_¢ = 0.165
 *
 *   - Sonnet call, 6000 input / 1000 fresh / 200 output:
 *       (Note: 1000 fresh = uncached; cached = 5000)
 *       Input: { inputTokens: 6000, cachedTokens: 5000, outputTokens: 200 }
 *       uncached = 1000
 *       cost_$ = (1000 × 3 + 200 × 15 + 5000 × 0.3) / 1M = $0.0075
 *       cost_¢ = 0.75
 */
export function computeAnthropicCostCents(input: AnthropicCostInput): number {
  validateInput(input);

  const pricing = ANTHROPIC_PRICING_USD_PER_M_TOKENS[input.tier];
  const cached = input.cachedTokens ?? 0;
  // Defensive: cached can't exceed total input. If a caller passes
  // inconsistent counts, clamp rather than throw (tests pin both behaviors).
  const clampedCached = Math.min(cached, input.inputTokens);
  const uncachedInput = input.inputTokens - clampedCached;

  const totalUsd =
    (uncachedInput * pricing.input +
      input.outputTokens * pricing.output +
      clampedCached * pricing.cached) /
    1_000_000;

  return totalUsd * 100;
}

// ===== Validation =====

function validateInput(input: AnthropicCostInput): void {
  if (!Number.isFinite(input.inputTokens) || input.inputTokens < 0) {
    throw new Error(
      `computeAnthropicCostCents: inputTokens must be a non-negative finite number (got ${input.inputTokens})`
    );
  }
  if (!Number.isFinite(input.outputTokens) || input.outputTokens < 0) {
    throw new Error(
      `computeAnthropicCostCents: outputTokens must be a non-negative finite number (got ${input.outputTokens})`
    );
  }
  if (
    input.cachedTokens !== undefined &&
    (!Number.isFinite(input.cachedTokens) || input.cachedTokens < 0)
  ) {
    throw new Error(
      `computeAnthropicCostCents: cachedTokens must be non-negative finite (got ${input.cachedTokens})`
    );
  }
  if (!ANTHROPIC_PRICING_USD_PER_M_TOKENS[input.tier]) {
    throw new Error(
      `computeAnthropicCostCents: unknown tier '${input.tier}'. ` +
        `Supported: ${Object.keys(ANTHROPIC_PRICING_USD_PER_M_TOKENS).join(', ')}`
    );
  }
}
